version: 2
jobs:
  build:
    working_directory: ~/xavier
    docker:
     - image: bepress/build-base:latest
    steps:
      - checkout

      - restore_cache:
          keys:
            - pip-{{ checksum "setup.py" }}-{{ checksum "test_requirements.txt" }}

      - run: make setup

      - save_cache:
          key: pip-{{ checksum "setup.py" }}-{{ checksum "test_requirements.txt" }}
          paths:
            - ~/xavier/.venv

      - run: make test
